### ISSUE TITLE
pyvm2.VirtualMachineError: unknown bytecode type: STORE_GLOBAL

### ISSUE THREAD

**Issue by z0rberg** [nedbat/byterun#21]
Greetings. I'm new here, so please accept my apology in case I'm doing this wrong.

Did you not implement the opcodes for "global" variables on purpose, or is it an oversight?

Am I the only one ever using it?

**Comment by llllllllll** [comment]
Thanks for the report! I checked and it does look like this opcode is missing. This is not a very common instruction so it must have been missed. I think the dispatch for this would look like:

```python
def byte_STORE_GLOBAL(self, name):
    self.frame.f_globals[name] = self.pop()
```

Would you like to open a pull request to add this and some test cases in `tests/test_function.py`? If not, I can try to get to this later this week.

**Comment by z0rberg** [comment]
Wow, a response! Amazing!

I never did anything like this. I'll see if I can work it all out and let you know if I don't.

**Comment by llllllllll** [comment]
Awesome, let me know if you have any questions along the way

**Comment by akaptur** [comment]
Agreed, there's no good reason for this to be missing. You can take a look at the implementation of `STORE_FAST` and `STORE_NAME` for suggestions. If you can add a test, too, that would be awesome.

**Comment by z0rberg** [comment]
I've sent a pull request. Yay my first. ^_^

Figured it out pretty quickly, just didn't have time to look into it earlier. I am not quite sure that the "test" actually makes any sense, but it's how i tested if it works.  I never used assert, ever and I wonder what all these "tests" actually do besides maybe causing errors.

**Comment by llllllllll** [comment]
Thanks for the quick fix, merged!

**Comment by akaptur** [comment]
If you're curious, you can take a look at the implementation of `assert_ok` here: https://github.com/nedbat/byterun/blob/master/tests/vmtest.py#L34
The basic strategy is to run code under byterun and under the real Python interpreter, and assert that it does the same thing in both cases. In this case we're using pytest asserts (like `assertEqual`) instead of the built-in Python assert, which gives us more detail when the test fails.

**Comment by z0rberg** [comment]
@llllllllll WOOHOO! : D

@akaptur Thank you, I'll look into it! It confused me too much not to!
